name = "Hyde"
license = "MIT"
licenselink = "https://github.com/spf13/hyde/blob/master/LICENSE.md"
description = "the data driven online marketing service."
tags = ["blog", "company"]
features = ["blog", "themes", "disqus"]
min_version = 0.14
